document.querySelector( "body > header > nav > img" ).onclick = e => {
	e.target.parentNode.classList.toggle( "opened" );
}

/* import du json*/
const img1 = document.getElementById('img')
const img2 = document.getElementById('img_2')
const img3 = document.getElementById('img_3')
const img4 = document.getElementById('img_4')
const img5 = document.getElementById('img_5')
const img6 = document.getElementById('img_6')
{
fetch("boutique.json")
	.then(Response => Response.json())	
	.then(data => img1.src = data.img_1)
fetch("boutique.json")
	.then(Response => Response.json())	
	.then(data =>document.querySelector("#name").innerHTML=data.name_1)
fetch("boutique.json")
	.then(Response => Response.json())
	.then(data =>document.querySelector("#description").innerHTML=data.description_1)
fetch("boutique.json")
	.then(Response => Response.json())
	.then(data =>document.querySelector("#prix").innerHTML=data.unit_price_1)
}
{
fetch("boutique.json")
	.then(Response => Response.json())	
	.then(data => img2.src = data.img_2)
fetch("boutique.json")
	.then(Response => Response.json())	
	.then(data =>document.querySelector("#name2").innerHTML=data.name_2)
fetch("boutique.json")
	.then(Response => Response.json())
	.then(data =>document.querySelector("#description2").innerHTML=data.description_2)
fetch("boutique.json")
	.then(Response => Response.json())
	.then(data =>document.querySelector("#prix2").innerHTML=data.unit_price_2)
}
{
fetch("boutique.json")
	.then(Response => Response.json())	
	.then(data => img3.src = data.img_3)
fetch("boutique.json")
	.then(Response => Response.json())	
	.then(data =>document.querySelector("#name3").innerHTML=data.name_3)
fetch("boutique.json")
	.then(Response => Response.json())
	.then(data =>document.querySelector("#description3").innerHTML=data.description_3)
fetch("boutique.json")
	.then(Response => Response.json())
	.then(data =>document.querySelector("#prix3").innerHTML=data.unit_price_3)
}
{
fetch("boutique.json")
	.then(Response => Response.json())	
	.then(data => img4.src = data.img_4)
fetch("boutique.json")
	.then(Response => Response.json())	
	.then(data =>document.querySelector("#name4").innerHTML=data.name_4)
fetch("boutique.json")
	.then(Response => Response.json())
	.then(data =>document.querySelector("#description4").innerHTML=data.description_4)
fetch("boutique.json")
	.then(Response => Response.json())
	.then(data =>document.querySelector("#prix4").innerHTML=data.unit_price_4)
}
{
fetch("boutique.json")
	.then(Response => Response.json())	
	.then(data => img5.src = data.img_5)
fetch("boutique.json")
	.then(Response => Response.json())	
	.then(data =>document.querySelector("#name5").innerHTML=data.name_5)
fetch("boutique.json")
	.then(Response => Response.json())
	.then(data =>document.querySelector("#description5").innerHTML=data.description_5)
fetch("boutique.json")
	.then(Response => Response.json())
	.then(data =>document.querySelector("#prix5").innerHTML=data.unit_price_5)
}
{			
fetch("boutique.json")
	.then(Response => Response.json())	
	.then(data => img6.src = data.img_6)
fetch("boutique.json")
	.then(Response => Response.json())	
	.then(data =>document.querySelector("#name6").innerHTML=data.name_6)
fetch("boutique.json")
	.then(Response => Response.json())
	.then(data =>document.querySelector("#description6").innerHTML=data.description_6)
fetch("boutique.json")
	.then(Response => Response.json())
	.then(data =>document.querySelector("#prix6").innerHTML=data.unit_price_6)
}
